version: '2'
services:
  spider:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: test-spider
    command: pm2-dev start process.dev.json --env
    ports:
      - 8081:8081
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:9.6.5-alpine
    volumes:
      - ./dbsource/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 111111
      PGDATA: /var/lib/postgresql/data/pgdata
